version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: patrickthedev/gitea-rpi
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8881:3000"
      - "2222:22"